## Desafio Data Engineer - Hurb

Desenvolvido por Gabriel Ribeiro Gomes, GitHub: [@gabrivoy](https://github.com/gabrivoy). *ribeiroggabriel@gmail.com* | *ribeirogabriel@poli.ufrj.br*.

---

Este notebook contém uma análise exploratória inicial dos arquivos comma-separated values (CSVs) "EstadosIBGE.csv" e "HIST_PAINEL_COVIDBR_28set2020.csv" disponibilizados para o desafio da posição de Data Scientist / Data Engineer do Hurb.

### Importações

In [2]:
import pandas as pd

### Análise do arquivo "EstadosIBGE.csv"

---

Inicialmente, criaremos uma variável chamada *df_estados* que receberá um pandas DataFrame contendo as informações do arquivo. Utilizaremos o método *read_csv()* juntamente com a informação que o delimitador do arquivo será feito por ponto-e-vírgula (;).

Usaremos o método *head()* para exibir os 5 primeiros valores do nosso dataframe, apresentando assim uma visualização inicial dos nossos dados.

In [13]:
df_estados = pd.read_csv("EstadosIBGE.csv", delimiter=";")
df_estados.head()

,UF [-],Código [-],Gentílico [-],Governador [2019],Capital [2010],Área Territorial - km² [2019],População estimada - pessoas [2020],Densidade demográfica - hab/km² [2010],Matrículas no ensino fundamental - matrículas [2018],IDH <span>Índice de desenvolvimento humano</span> [2010],Receitas realizadas - R$ (×1000) [2017],Despesas empenhadas - R$ (×1000) [2017],Rendimento mensal domiciliar per capita - R$ [2019],Total de veículos - veículos [2018]
0,Acre,12,acriano,GLADSON DE LIMA CAMELI,Rio Branco,"164123,964",894470,"4,47",157646,"0,663","6632883,108","6084416,806",890,277831
1,Alagoas,27,alagoano,JOSE RENAN VASCONCELOS CALHEIROS FILHO,Maceió,"27843,295",3351543,"112,33",490587,"0,631","11950438,46","10460634,92",731,834827
2,Amapá,16,amapaense,ANTONIO WALDEZ GÓES DA SILVA,Macapá,"142470,762",861773,"4,69",136185,"0,708","5396417,145","4224464,088",880,195039
3,Amazonas,13,amazonense,WILSON MIRANDA LIMA,Manaus,"1559167,889",4207714,"2,23",705007,"0,674","17328459,43","15324896,56",842,883083
4,Bahia,29,baiano,RUI COSTA DOS SANTOS,Salvador,"564760,427",14930634,"24,82",2034711,"0,66","50191003,24",45570160,913,4139107

Com o método *info()* conseguimos extrair informações importantes acerca da estruturação dos dados dentro do DataFrame.

Assim, conseguimos as seguintes informações primárias dos dados:

* Número de colunas: 14
* Número de linhas: 27
* Tipos de dados: 'object' e 'int64' (provavelmente strings e inteiros, mas analisaremos melhor posteriormente)
* Não temos valores nulos no dataset

In [15]:
df_estados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 14 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   UF [-]                                                     27 non-null     object
 1   Código [-]                                                 27 non-null     int64
 2   Gentílico [-]                                              27 non-null     object
 3   Governador [2019]                                          27 non-null     object
 4   Capital [2010]                                             27 non-null     object
 5   Área Territorial - km² [2019]                              27 non-null     object
 6   População estimada - pessoas [2020]                        27 non-null     int64
 7   Densidade demográfica - hab/km² [2010]                     27 non-null     object
 8   Matrículas no ensino fundamental - matrículas [2018]      27 non-null     int64
 9   IDH <span>Índice de desenvolvimento humano</span> [2010]  27 non-null     object
 10  Receitas realizadas - R$ (×1000) [2017]                    27 non-null     object
 11  Despesas empenhadas - R$ (×1000) [2017]                    27 non-null     object
 12  Rendimento mensal domiciliar per capita - R$ [2019]        27 non-null     int64
 13  Total de veículos - veículos [2018]                        27 non-null     int64
dtypes: int64(5), object(9)
memory usage: 3.1+ KB

Podemos verificar que o dataset possui alguns dados numéricos que podem ser representados pelo tipo 'float', por se tratarem de números com vírgula. As colunas que poderiam ser formatadas com essa relação são:

* Área Territorial - km² [2019]
* Densidade demográfica - hab/km² [2010]
* IDH - Índice de desenvolvimento humano [2010]
* Receitas realizadas - R\$ (×1000) [2017]
* Despesas empenhadas - R\$ (×1000) [2017]

Usamos também o método *describe()* para extrair alguns dados estatísticos do dataset como média, desvio padrão, valor mínimo e máximo, entre outros.

In [21]:
df_estados.describe()

,Código [-],População estimada - pessoas [2020],Matrículas no ensino fundamental - matrículas [2018],Rendimento mensal domiciliar per capita - R$ [2019],Total de veículos - veículos [2018]
count,27.000000,2.700000e+01,2.700000e+01,27.000000,2.700000e+01
mean,29.111111,7.842803e+06,1.006814e+06,1238.703704,3.731354e+06
std,13.024631,9.316952e+06,1.079327e+06,476.693968,5.729603e+06
min,11.000000,6.311810e+05,9.658200e+04,636.000000,1.950390e+05
25%,19.000000,2.932272e+06,3.908680e+05,901.500000,9.340650e+05
50%,27.000000,4.064052e+06,5.562480e+05,1056.000000,1.812473e+06
75%,38.000000,9.401862e+06,1.300333e+06,1495.500000,4.024268e+06
max,53.000000,4.628933e+07,5.367614e+06,2686.000000,2.905775e+07

### Análise do arquivo "HIST_PAINEL_COVIDBR_28set2020.csv"

---

Seguiremos o mesmo padrão do arquivo anterior na análise exploratória desse. Criaremos uma variável chamada *df_covidbr* que receberá um pandas DataFrame contendo as informações do arquivo e utilizaremos *read_csv()* e o delimitador (;).

Usaremos o método *head()* para exibir os 5 primeiros valores do nosso dataframe, apresentando assim uma visualização inicial dos nossos dados.

In [20]:
df_covidbr = pd.read_csv("HIST_PAINEL_COVIDBR_28set2020.csv", delimiter=";")
df_covidbr.head()

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,25/02/2020,9,210147125.0,0,0,0,0,NaN,NaN,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,26/02/2020,9,210147125.0,1,1,0,0,NaN,NaN,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,27/02/2020,9,210147125.0,1,0,0,0,NaN,NaN,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,28/02/2020,9,210147125.0,1,0,0,0,NaN,NaN,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,29/02/2020,9,210147125.0,2,1,0,0,NaN,NaN,NaN

Com o método *info()* conseguimos extrair informações importantes acerca da estruturação dos dados dentro do DataFrame.

Assim, conseguimos as seguintes informações primárias dos dados:

* Número de colunas: 17
* Número de linhas: 1.045.816 (um milhão, quarenta e cinco mil e oitocentos e dezesseis)
* Tipos de dados: 'object' e 'int64'
* **Temos** valores nulos no dataset

In [16]:
df_covidbr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045816 entries, 0 to 1045815
Data columns (total 17 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   regiao                  1045816 non-null  object
 1   estado                  1045599 non-null  object
 2   municipio               1035834 non-null  object
 3   coduf                   1045816 non-null  int64
 4   codmun                  1039740 non-null  float64
 5   codRegiaoSaude          1035834 non-null  float64
 6   nomeRegiaoSaude         1035834 non-null  object
 7   data                    1045816 non-null  object
 8   semanaEpi               1045816 non-null  int64
 9   populacaoTCU2019        1041910 non-null  float64
 10  casosAcumulado          1045816 non-null  int64
 11  casosNovos              1045816 non-null  int64
 12  obitosAcumulado         1045816 non-null  int64
 13  obitosNovos             1045816 non-null  int64
 14  Recuperadosnovos        163 non-null      float64
 15  emAcompanhamentoNovos   163 non-null      float64
 16  interior/metropolitana  1035834 non-null  float64
dtypes: float64(6), int64(6), object(5)
memory usage: 135.6+ MB

Além disso, podemos verificar que, por se tratar de um dataset com um grande número de linhas, podemos nos beneficiar do uso da função *tail()* também, para ver os 5 dados finais do nosso arquivo.

In [23]:
df_covidbr.tail()

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
1045811,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,24/09/2020,39,3015268.0,186945,893,3164,16,NaN,NaN,1.0
1045812,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,25/09/2020,39,3015268.0,187895,950,3175,11,NaN,NaN,1.0
1045813,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,26/09/2020,39,3015268.0,188608,713,3183,8,NaN,NaN,1.0
1045814,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,27/09/2020,40,3015268.0,189513,905,3188,5,NaN,NaN,1.0
1045815,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,28/09/2020,40,3015268.0,190505,992,3203,15,NaN,NaN,1.0

In [22]:
df_covidbr.describe()

,coduf,codmun,codRegiaoSaude,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
count,1.045816e+06,1.039740e+06,1.035834e+06,1.045816e+06,1.041910e+06,1.045816e+06,1.045816e+06,1.045816e+06,1.045816e+06,1.630000e+02,163.000000,1.035834e+06
mean,3.235719e+01,3.252392e+05,3.240122e+04,2.648714e+01,1.250501e+05,9.328984e+02,1.361271e+01,3.259524e+01,4.075038e-01,1.447975e+06,475605.263804,6.931226e-02
std,9.878967e+00,9.853381e+04,9.836198e+03,7.688399e+00,3.168012e+06,3.288514e+04,4.341171e+02,1.096452e+03,1.236230e+01,1.335031e+06,251008.063954,2.539845e-01
min,1.100000e+01,1.100000e+05,1.100100e+04,9.000000e+00,7.810000e+02,0.000000e+00,-7.926000e+03,0.000000e+00,-2.920000e+02,2.213000e+04,14062.000000,0.000000e+00
25%,2.500000e+01,2.512000e+05,2.501000e+04,2.000000e+01,5.476000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.951840e+05,258263.000000,0.000000e+00
50%,3.100000e+01,3.146050e+05,3.105900e+04,2.600000e+01,1.171000e+04,1.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.054043e+06,556507.000000,0.000000e+00
75%,4.100000e+01,4.119100e+05,4.101500e+04,3.300000e+01,2.587700e+04,1.150000e+02,1.000000e+00,3.000000e+00,0.000000e+00,2.584716e+06,671253.000000,0.000000e+00
max,7.600000e+01,5.300100e+05,5.300100e+04,4.000000e+01,2.101471e+08,4.745464e+06,6.907400e+04,1.420580e+05,1.595000e+03,4.084182e+06,817642.000000,1.000000e+00

### Analisando o pipeline

O objetivo é gerar um CSV oriundo de informações específicas de cada um dos datasets. As colunas do dataset gerado devem ser: